In [2]:
import sympy as sm

In [3]:
ϕ, θ, u1, v1, m1, m2 = sm.symbols("ϕ, θ, u1, v1, m1, m2")

In [4]:
cos_phi = (m1 + m2*sm.cos(ϕ))/(m1+m2)

In [5]:
sin_phi = sm.sqrt(1-cos_phi**2)

In [6]:
tan_phi = sm.simplify(sin_phi/cos_phi)

In [7]:
def do():
    import numpy as np
    x=2
    m1=4
    m2=12
    return np.sin(x)/(np.cos(x)+m1/m2)
do()

-10.980062327251687

In [8]:
tan_phi.subs({ϕ:2,m1:4,m2:12}).evalf()


-16.0693488140098

In [10]:
import bqplot.pyplot as plt

In [12]:
import ipywidgets as w
import numpy as np

In [281]:
fig = plt.figure()
b2 = plt.plot([],[],'y--', labels=['2.f'])
b1 = plt.plot([],[],'y', labels=['2.i'])
c = plt.plot([],[],'r', labels=['1.f'])
plt.legend();

In [282]:
def rot(θ):
    return np.array([
        [np.cos(θ), -np.sin(θ)],
        [np.sin(θ), np.cos(θ)]
    ])    

In [283]:
@w.interact(θ=(0.5,180), u_x=(0.0,10), m_1=(1, 10), m_2=(1,10), momentum=False)
def plot(θ, u_x, m_1, m_2, momentum):
    θ = np.radians(θ)
    α = m_1 / (m_1 + m_2)
    u_1 = np.array([u_x, 0])
    v_1 = (1-α)*(u_1@rot(θ).T) + α*u_1
    v_2 = α*(u_1@(np.identity(2)+rot(θ+np.pi).T))
    
    if momentum:
        out_2 = v_2 * m_2
        out_1 = v_1 * m_1
        out_0 = u_1 * m_1
        fig.title = "Momentum plot"
    else:
        out_2 = v_2
        out_1 = v_1
        out_0 = u_1
        fig.title = "Velocity plot"

    c.x = [0, out_2[0]]
    c.y = [0, out_2[1]]
    
    b1.x = [-out_0[0], 0]
    b1.y = [-out_0[1], 0]
    
    b2.x = [0, out_1[0]]
    b2.y = [0, out_1[1]]  
    
fig

interactive(children=(FloatSlider(value=90.25, description='θ', max=180.0, min=0.5), FloatSlider(value=5.0, de…

Figure(axes=[Axis(scale=LinearScale(), side='bottom'), Axis(orientation='vertical', scale=LinearScale(), side=…

In [308]:
θ = 140
m_1 = 10
m_2 = 10
u_x = 5

α = m_1 / (m_1 + m_2)
u_1 = np.array([u_x, 0])

In [309]:
θ = np.linspace(0, 2*np.pi)

In [310]:
plt.figure()
plt.plot(θ, np.arctan(np.sin(θ)/(np.cos(θ)+m_1/m_2)))
plt.show()

# Compare methods

In [311]:

v_1 = (1-α)*(u_1@rot(θ).T) + α*u_1
v_2 = α*(u_1@(np.identity(2)+rot(θ+np.pi).T))

cos_ϕ = np.dot(v_1, u_1) / (np.linalg.norm(v_1)*np.linalg.norm(u_1))
cos_θ = np.cos(θ)
cos_ϕ

array([0.19802951, 0.1972166 , 0.19479122, 0.19079319, 0.18528816,
       0.17836653, 0.17014194, 0.16074944, 0.15034327, 0.13909428,
       0.12718718, 0.1148175 , 0.10218833, 0.08950706, 0.0769819 ,
       0.06481852, 0.05321664, 0.04236676, 0.03244705, 0.02362037,
       0.01603167, 0.00980554, 0.00504423, 0.00182592, 0.00020344,
       0.00020344, 0.00182592, 0.00504423, 0.00980554, 0.01603167,
       0.02362037, 0.03244705, 0.04236676, 0.05321664, 0.06481852,
       0.0769819 , 0.08950706, 0.10218833, 0.1148175 , 0.12718718,
       0.13909428, 0.15034327, 0.16074944, 0.17014194, 0.17836653,
       0.18528816, 0.19079319, 0.19479122, 0.1972166 , 0.19802951])

In [312]:
from scipy.optimize import curve_fit
def f(x, m, c):
    return m*x + c
popt, _ = curve_fit(f, cos_θ, np.dot(v_1,u_1))
popt

array([12.5, 12.5])

---

In [313]:
cos_θ = np.dot(v_1,u_1)/(np.linalg.norm(u_1)*np.linalg.norm(v_1, axis=-1))
cos_θ

array([1.        , 0.99794539, 0.99179001, 0.98155916, 0.96729486,
       0.94905575, 0.92691676, 0.90096887, 0.8713187 , 0.8380881 ,
       0.80141362, 0.76144596, 0.71834935, 0.67230089, 0.6234898 ,
       0.57211666, 0.51839257, 0.46253829, 0.40478334, 0.34536505,
       0.28452759, 0.22252093, 0.1595999 , 0.09602303, 0.03205158,
       0.03205158, 0.09602303, 0.1595999 , 0.22252093, 0.28452759,
       0.34536505, 0.40478334, 0.46253829, 0.51839257, 0.57211666,
       0.6234898 , 0.67230089, 0.71834935, 0.76144596, 0.80141362,
       0.8380881 , 0.8713187 , 0.90096887, 0.92691676, 0.94905575,
       0.96729486, 0.98155916, 0.99179001, 0.99794539, 1.        ])

In [314]:
1-4*m_1*m_2/(m_1+m_2)**2*np.cos(θ)**2

array([0.        , 0.01635257, 0.06434065, 0.14082532, 0.24080372,
       0.35773621, 0.48397421, 0.61126047, 0.73126915, 0.83615045,
       0.91904405, 0.97452787, 0.9989727 , 0.99077958, 0.95048443,
       0.88072298, 0.78605833, 0.67268253, 0.54801151, 0.42020005,
       0.29760833, 0.1882551 , 0.09929319, 0.03654162, 0.00410499,
       0.00410499, 0.03654162, 0.09929319, 0.1882551 , 0.29760833,
       0.42020005, 0.54801151, 0.67268253, 0.78605833, 0.88072298,
       0.95048443, 0.99077958, 0.9989727 , 0.97452787, 0.91904405,
       0.83615045, 0.73126915, 0.61126047, 0.48397421, 0.35773621,
       0.24080372, 0.14082532, 0.06434065, 0.01635257, 0.        ])

In [315]:
np.degrees(np.arctan(np.sin(θ) / (np.cos(θ)+m_1/m_2)))

array([ 0.00000000e+00,  3.67346939e+00,  7.34693878e+00,  1.10204082e+01,
        1.46938776e+01,  1.83673469e+01,  2.20408163e+01,  2.57142857e+01,
        2.93877551e+01,  3.30612245e+01,  3.67346939e+01,  4.04081633e+01,
        4.40816327e+01,  4.77551020e+01,  5.14285714e+01,  5.51020408e+01,
        5.87755102e+01,  6.24489796e+01,  6.61224490e+01,  6.97959184e+01,
        7.34693878e+01,  7.71428571e+01,  8.08163265e+01,  8.44897959e+01,
        8.81632653e+01, -8.81632653e+01, -8.44897959e+01, -8.08163265e+01,
       -7.71428571e+01, -7.34693878e+01, -6.97959184e+01, -6.61224490e+01,
       -6.24489796e+01, -5.87755102e+01, -5.51020408e+01, -5.14285714e+01,
       -4.77551020e+01, -4.40816327e+01, -4.04081633e+01, -3.67346939e+01,
       -3.30612245e+01, -2.93877551e+01, -2.57142857e+01, -2.20408163e+01,
       -1.83673469e+01, -1.46938776e+01, -1.10204082e+01, -7.34693878e+00,
       -3.67346939e+00, -7.01670930e-15])

In [316]:
plt.figure()
plt.plot(θ, np.degrees(np.arctan(np.sin(θ) / (np.cos(θ)+m_1/m_2))))
plt.show()

In [325]:
from numpy.linalg import norm

np.dot(v_1, u_1)*((1-α)*np.cos(θ)+α)*norm(u_1, axis=-1)**2

array([6.25000000e+02, 6.19879290e+02, 6.04726418e+02, 5.80157530e+02,
       5.47161514e+02, 5.07045475e+02, 4.61363201e+02, 4.11831115e+02,
       3.60236874e+02, 3.08346288e+02, 2.57814238e+02, 2.10104987e+02,
       1.66426634e+02, 1.27683495e+02, 9.44490153e+01, 6.69604550e+01,
       4.51351702e+01, 2.86068988e+01, 1.67791729e+01, 8.89187981e+00,
       4.09616590e+00, 1.53236955e+00, 4.05518268e-01, 5.31351080e-02,
       6.59595461e-04, 6.59595461e-04, 5.31351080e-02, 4.05518268e-01,
       1.53236955e+00, 4.09616590e+00, 8.89187981e+00, 1.67791729e+01,
       2.86068988e+01, 4.51351702e+01, 6.69604550e+01, 9.44490153e+01,
       1.27683495e+02, 1.66426634e+02, 2.10104987e+02, 2.57814238e+02,
       3.08346288e+02, 3.60236874e+02, 4.11831115e+02, 4.61363201e+02,
       5.07045475e+02, 5.47161514e+02, 5.80157530e+02, 6.04726418e+02,
       6.19879290e+02, 6.25000000e+02])